- type: job
  id: Captain
  name: Ариец
  description: ЗИГ ХАЙЛЬ СЛАВА ГИТЛЕРУ СМЕРТЬ ЖИДАМ
  playTimeTracker: JobCaptain
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    id: CaptainIDCard
  storage:
    back:
    - BaseUplinkRadio
    - KnifeClaimer
    # - StationCharter
