- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxSilly
  - CorvaxOutpost
  - CorvaxAstra
  - CorvaxGelta
  - CorvaxMaus
  - CorvaxIshimura
  - CorvaxPaper
  - CorvaxPilgrim
  - CorvaxSplit
  - CorvaxTerra
  - Train
