- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  # Highpop
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxAstra
  - CorvaxPilgrim
  - CorvaxGlacier
  - Box # reserve
  # Midpop
  - CorvaxPaper
  - CorvaxPearl
  - Bagel
  - Marathon
  #- Train # reserve
  # Lowpop
  - CorvaxSilly
  - CorvaxMaus
  - CorvaxTushkan
  - Packed
  #- Omega # reserve
