- type: job
  id: SAI
  name: job-name-sai
  description: job-description-sai
  playTimeTracker: JobSAI
  requirements:
  - !type:AdminRoleRequirement
    role: LoyalAi
  weight: 30
  icon: JobIconStationAI
  supervisors: "all crew"
  accessGroups:
    - AllAccess
  canBeAntag: false
  jobEntity: AICore
  startingGear: CentcomAdmiralGear # for char preview only
  alwaysUseSpawner: true
  #canHaveTraits: false
  joinNotifyCrew: true
  whitelistRequired: true

# - type: startingGear
#   id: AIGear
#   equipment:
#     id: AIPDA
#   inhand:
#     hand 1: AIPDA
#     hand 2: DoorRemoteAI
# - type: startingGear
#   id: AIGearUnremoveable
#   equipment:
#     id: AIPDAur
#   inhand:
#     hand 1: AIPDAur
#     hand 2: DoorRemoteAIur
