- type: job
  id: StarDustOfficer
  name: job-name-star-dust-officer
  description: job-description-star-dust-officer
  playTimeTracker: JobStarDustOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 54000 #25 hrs # Corvax-RoleTime
  startingGear: StarDustOfficerGear
  icon: "JobIconStarDustOfficer"
  supervisors: job-supervisors-star-dust-officer
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Detective
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: StarDustOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitStarDustOfficer
    back: ClothingBackpackSecurityFilled
    head: ClothingHeadHatBeretHoS
    eyes: ClothingEyesGlassesSecurity
    shoes: ClothingShoesBootsCombatFilled
    id: SecurityPDA
    ears: ClothingHeadsetAltSecurity
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolG22NonLethal
    outerClothing: ClothingOuterVestArmorSec
  innerClothingSkirt: ClothingUniformJumpsuitStarDustOfficer
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
